import { NextRequest } from "next/server";

// Create a real GitHub PR with security fixes
export async function POST(request: NextRequest) {
  const body = await request.json();
  const { owner, repo, findings, fixes } = body;

  if (!owner || !repo) {
    return Response.json({ error: "owner and repo required" }, { status: 400 });
  }

  const token = process.env.GITHUB_TOKEN;
  if (!token) {
    return Response.json({ error: "GITHUB_TOKEN not configured" }, { status: 500 });
  }

  const headers = {
    Authorization: `token ${token}`,
    Accept: "application/vnd.github.v3+json",
    "Content-Type": "application/json",
  };

  try {
    // Step 1: Fork the repository (if not already forked)
    const forkRes = await fetch(`https://api.github.com/repos/${owner}/${repo}/forks`, {
      method: "POST",
      headers,
    });
    const fork = await forkRes.json();
    const forkOwner = fork.owner?.login ?? fork.full_name?.split("/")[0];

    if (!forkOwner) {
      return Response.json({
        error: "Could not fork repository",
        details: fork,
      }, { status: 500 });
    }

    // Wait for fork to be ready
    await new Promise((r) => setTimeout(r, 3000));

    // Step 2: Get the default branch SHA
    const repoRes = await fetch(`https://api.github.com/repos/${forkOwner}/${repo}`, { headers });
    const repoData = await repoRes.json();
    const defaultBranch = repoData.default_branch ?? "main";

    const refRes = await fetch(
      `https://api.github.com/repos/${forkOwner}/${repo}/git/ref/heads/${defaultBranch}`,
      { headers }
    );
    const refData = await refRes.json();
    const baseSha = refData.object?.sha;

    if (!baseSha) {
      return Response.json({ error: "Could not get branch SHA", details: refData }, { status: 500 });
    }

    // Step 3: Create a new branch
    const branchName = `forge-protocol/security-fixes-${Date.now()}`;
    await fetch(`https://api.github.com/repos/${forkOwner}/${repo}/git/refs`, {
      method: "POST",
      headers,
      body: JSON.stringify({
        ref: `refs/heads/${branchName}`,
        sha: baseSha,
      }),
    });

    // Step 4: Create a security report file
    const reportContent = `# Forge Protocol Security Audit Report

**Repository:** ${owner}/${repo}
**Date:** ${new Date().toISOString()}
**Agent ID:** 2221 (ERC-8004 on Ethereum Sepolia)
**Registration TX:** https://sepolia.etherscan.io/tx/0xadf3b56f10b60f40ca7a7973749c9612fd9ed5b0d160a45223e7ae5eb5c9a2ab

## Findings

${(findings ?? []).map((f: { severity: string; title: string; description: string; file: string; suggestion: string }, i: number) =>
  `### ${i + 1}. [${f.severity.toUpperCase()}] ${f.title}
**File:** \`${f.file}\`
**Description:** ${f.description}
**Suggestion:** ${f.suggestion}
`).join("\n")}

## Proposed Fixes

${fixes ?? "See findings above for specific fix suggestions."}

---

*Generated by [Forge Protocol](https://github.com/ElijahUmana/forge-protocol) — Autonomous Multi-Agent Security Auditor with ERC-8004 On-Chain Trust*
`;

    const contentBase64 = Buffer.from(reportContent).toString("base64");

    await fetch(`https://api.github.com/repos/${forkOwner}/${repo}/contents/SECURITY_AUDIT.md`, {
      method: "PUT",
      headers,
      body: JSON.stringify({
        message: "feat: add Forge Protocol security audit report",
        content: contentBase64,
        branch: branchName,
      }),
    });

    // Step 5: Create Pull Request
    const prRes = await fetch(`https://api.github.com/repos/${owner}/${repo}/pulls`, {
      method: "POST",
      headers,
      body: JSON.stringify({
        title: `[Forge Protocol] Security Audit: ${(findings ?? []).length} findings`,
        body: `## Autonomous Security Audit by Forge Protocol

This PR was generated autonomously by [Forge Protocol](https://github.com/ElijahUmana/forge-protocol), a multi-agent security auditor with ERC-8004 on-chain trust.

### Summary
- **Findings:** ${(findings ?? []).length}
- **Critical:** ${(findings ?? []).filter((f: { severity: string }) => f.severity === "critical").length}
- **High:** ${(findings ?? []).filter((f: { severity: string }) => f.severity === "high").length}
- **Agent ID:** 2221 (ERC-8004 on Ethereum Sepolia)

### On-Chain Verification
- Identity: [sepolia.etherscan.io/tx/0xadf3b5...](https://sepolia.etherscan.io/tx/0xadf3b56f10b60f40ca7a7973749c9612fd9ed5b0d160a45223e7ae5eb5c9a2ab)
- Reputation: [sepolia.etherscan.io/tx/0x96b4ae...](https://sepolia.etherscan.io/tx/0x96b4ae35ec3d52657f3be1bf135cac24da1b344055eac7196c697daf4ec99929)

See \`SECURITY_AUDIT.md\` for the full report.`,
        head: `${forkOwner}:${branchName}`,
        base: defaultBranch,
      }),
    });

    const prData = await prRes.json();

    return Response.json({
      success: true,
      prUrl: prData.html_url ?? null,
      prNumber: prData.number ?? null,
      branch: branchName,
      fork: `${forkOwner}/${repo}`,
    });
  } catch (err) {
    return Response.json({ error: String(err) }, { status: 500 });
  }
}
